// AidLoop Contract Addresses on Stellar Testnet
export const CONTRACTS = {
  IMPACT_VAULT: 'CCCZ7BFJIM7O4XXZK22P6ZXGPM6NNWDZXR4U3YTE5WI6ITTA342HAICW',
  IMPACT_CONTRACT: 'CCG6HA73JOZIJB7W5WGMXORZN4SECNI2HB2DMM4KXUSSCGD6SSG657FY', // Using MerchantRegistry for proof submission
  PROGRAM_MANAGER: 'CDG2DJOKXE4MD7MCG5OAPBPLODROJ2AADW75EUSPMONCLPXVVYD5AVKN',
  VOUCHER_MANAGER: 'CCTKNEL4UPLCTQSLIHE2Y3RIDFZKUTBONYFXSOOS2MSDU3YLRCCXSEIG',
  MERCHANT_REGISTRY: 'CA4ED4DJ4T7BCP26A2GOVY5Z2CANXRM23DVPT352LQYMAJCSGF757GZN',
  IMPACT_CREDIT_NFT: 'CA2PWCZSTCIZ75JRWXRIGU2LA7K25FZT2LMYRGJHXYTAJXK7PMURPUX2',
} as const;

export const NETWORK = {
  name: 'testnet',
  rpcUrl: 'https://soroban-testnet.stellar.org',
  networkPassphrase: 'Test SDF Network ; September 2015',
  horizonUrl: 'https://horizon-testnet.stellar.org',
} as const;

// USDC Stellar Asset Contract on Testnet
// This is the Soroban contract address for USDC:GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5
export const USDC_TOKEN = 'CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA';

// USDC Asset Issuer (for trustlines and balance checks)
export const USDC_ISSUER = 'GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5';

// Deployer address (admin)
export const ADMIN_ADDRESS = 'GAEFBBEVPIUUOTKWOL7B3L6X46F5HYFY5E2IUDV2EUA3LOO6C5AJVB35';

